################################################################
#                                                              #
# Author: Foivos S. Zakkak                                     #
#                                                              #
################################################################

all:
	@echo "Please read the User Manual first!!!"

.PHONY: doc javadoc

doc:
	@make -C ../doc/manual -s

javadoc:
	@./d -javadoc
